title: Primal Fitness Drogheda
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jastew.github.io"
logo: /assets/img/logo.png
location: Greenhills Industrial Village, Greenhills, Drogheda, Co.Louth, Ireland
phone: 086 190 4801
email: primalfitness101@gmail.com
facebook: https://www.facebook.com/Primalfitnessdrogheda
youtube: https://www.youtube.com/channel/UCzeWN3V8ECuDGAJlNHG5HAg
instagram: https://www.instagram.com/primalfitnessdrogheda/

collections:
  classes:
    output: true
  transformations:
    output: true

permalink: pretty

gender:
  - male
  - female

defaults:
  - scope:
      path: ""
    values:
      type: website
      title:
      banner_image:
  - scope:
      type: posts
    values:
      permalink: /blog/:title/
      description:
      type: article
      image: 'http://placehold.it/400x200&text=post'
      is_post: true
  - scope:
      type: transformations
    values:
      layout: transformation
      permalink: /stories/:title/
      type: article
      title:
      gender:
      date: 2017-01-01 00:00:00
      description:
      image:
      images:
        - image:
  - scope:
      type: classes
    values:
      layout: class

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.js
  - gulpfile.js
