menu_items:
    - label: Home
      link: /
    - label: About Us
      link: /about
    - label: Classes
      link: /classes
    - label: Stories
      link: /stories
contact:
    location: Greenhills Industrial Village, Greenhills, Drogheda, Co.Louth, Ireland
    phone: 086 190 4801
    email: primalfitness101@gmail.com
    facebook: https://www.facebook.com/Primalfitnessdrogheda
    youtube: https://www.youtube.com/channel/UCzeWN3V8ECuDGAJlNHG5HAg
    instagram: https://www.instagram.com/primalfitnessdrogheda/