- name: Ben Cunningham
  description: 'Interesting Fact : Ben started his Personal trainer journey equipped with three kettlebells and a barbell in his mothers back garden. Eight years on and hes still just as passionate about helping people achieve there goals as when he first started.'
  image: /uploads/19029512-635938206594747-3202868902361079227-n.jpg
- name: Stephen Walsh
  description: 'Interesting Fact : Stephen was a butcher by trade in a past life. As a result, he is no stranger to the kitchen. His knowledge on nutrition and tasty healthy recipes is a integral part of what keep our members diets on track and consistent.'
  image: /uploads/13494842-493056160882953-7123349173500502491-n.jpg
- name: Anna Stafford
  description: 'Interesting Fact : Anna has competed in numerous Tactical strength competitions and in 2015  she ranked in the top 30 world wide.'
  image: /uploads/screenshot-2017-07-24-16-46-53.png